api:
  port: 42233
superCode: 123456
redis:
  dbAddress: redis:6379
  dbMaxIdle: 128
  dbMaxActive: 0
  dbIdleTimeout: 120
  dbPassWord: vyTB3bHklcHZnjx

mysql:
  dbAddress: mysql8
  dbUserName: root
  dbPassword: FFS0PG3pBWZ3dji6Yn
  dbName: openIM
  dbMaxOpenConns: 20
  dbMaxIdleConns: 10
  dbMaxLifeTime: 120


alibabacloud:
  accessKeyId:
  accessKeySecret:
  SignName:
  VerificationCodeTemplateCode:


imserver:
  ip: open-im-server
  secret: tuoyun
  superCode: 666666


log:
  storageLocation: ./logs/
  rotationTime: 12
  remainRotationCount: 10
  elasticSearchSwitch: false
  elasticSearchAddr: [ 127.0.0.1:9201 ]
  elasticSearchUser: ""
  elasticSearchPassword: ""


